### PR TITLE
ARE New Zombie Execution Error

### PR DESCRIPTION
**Pull request by jackdwalker**
Thanks for submitting a PR! Please fill in this template where appropriate:

## Category

Bug

## Feature/Issue Description

This fix solves the error described in issue [1932](https://github.com/beefproject/beef/issues/1932).

## Describe What Changes 

As per my description in the issue:

> During the Autorun execution process there was an issue with the `BeEF::Core::Models::Execution` object that was created. The function creating it was creating it with a `:rule_id` key (see lines 88 → 96 in `core/main/autorun_engine/engine.rb`). According to the `executions` object in the [Database Schema](https://github.com/beefproject/beef/wiki/Database-Schema#executions) page in the Wiki, this key should simply be called `:id`. This small change seemed to fix the problem!

## Test Cases

N/A

## Relevant Wiki Page

[AutoRunEngine](https://github.com/beefproject/beef/wiki/Autorun-Rule-Engine)
[Database Schema - Execution Model](https://github.com/beefproject/beef/wiki/Database-Schema#executions)

### CODE REVIEW

**Comment by jcrew99** [comment]
Right, this seems to work locally but i haven't been able to receive the same error when running the auto run rules either. Has pinkbat1's issue been resolved by the change or have you been able to fix the error fully with the change? ( i saw you said you got it locally)

**Comment by jackdwalker** [comment]
@jcrew99 - I was able to reproduce his error by following the steps he outlined in the issue template. This patch fixed the error he was receiving :)

**Comment by jcrew99** [comment]
Cool, great work on it!

**Comment by bcoles** [comment]
The issue was that the schema was missing the `:rule_id` attribute and the Autorun Engine attempting to store executions using the `session` attribute instead of `session_id`. This was later patched in d417645b286a9e2799d3cc970aff6a0479b94c2e.

The patch in this PR was later reverted in #2782.

**Pull request merged**
