### PR TITLE
Removed two Chrome module that no longer work.

### PR DESCRIPTION
**Pull request by Fuitad**
Removed two Chrome module that no longer work. chrome.cookies and chrome.tabs no longer exists

### CODE REVIEW

**Comment by bcoles** [comment]
Generally I would prefer modifying the `working` / `not_working` properties of the command module's associated `config.yaml` to reflect the supported browser versions, rather than removing the module.

Do you have a reference to the removal?

**Comment by Fuitad** [comment]
Wow, that's a quick reply!

I'm sorry, I had no idea about the working/not working. I shall look for references and properly update my commit.

**Comment by bcoles** [comment]
Thanks, and thanks for bringing it to our attention.

**Comment by Fuitad** [comment]
From what I can see, these parameters still do exist, however, the chrome.cookies and chrome.tabs API can only be used by extensions who have declared these permissions in their manifest file.

Should we just remove from from working:[] for the time being?

**Pull request closed without merging**
