### PR TITLE
Fix modules for Metasploit v6.1.10-dev

### PR DESCRIPTION
**Pull request by wanetty**
# Pull Request

Thanks for submitting a PR! Please fill in this template where appropriate:

## Category
Bug

## Feature/Issue Description
**Q:** Please give a brief summary of your feature/fix
**A:**  I have adapted the bind_shell modules for metasploit version 6.1.10-dev.

**Q:** Give a technical rundown of what you have changed (if applicable)
**A:** Module names have been changed, as metasploit did not recognise the module with capital letters in the name.

## Test Cases
**Q:** Describe your test cases, what you have covered and if there are any use cases that still need addressing.
**A:**I started metasploit and msfvenom and it was already detecting the cases. Previously it gave an error and no module was started.

## Wiki Page
*If you are adding a new feature that is not easily understood without context, please draft a section to be added to the Wiki below.*

### CODE REVIEW

**Comment by DeezyE** [comment]
Hi @wanetty thanks for the PR. Just to be clear, Metasploit wouldn't recognise "BeEFBind" but it does "BeefBind" ? Was that a change on Metasploit end?

**Comment by wanetty** [comment]
> 
> 
> Hi @wanetty thanks for the PR. Just to be clear, Metasploit wouldn't recognise "BeEFBind" but it does "BeefBind" ? Was that a change on Metasploit end?

Hi @DeezyE !  I'm not sure, but I don't know if metasploit requires its module names to start with capital letters or if it's a new ruby rule.

I was looking at a lot of alternatives because I didn't understand that Metasploit was telling me that it couldn't find beefbind defined in the autoload. The only thing I changed was to change the name to how they were defined in the other methods.

If you can provide a more technical explanation I would appreciate it.

**Comment by DeezyE** [comment]
I've not looked at Metasploit, but I assume they are using strict Ruby styleguide when calling Methods...
I'll move this along the merging process.

Also if you're keen to do further dev with us on beef we'd be happy to have you join our discord. email discord@bindshell.net and we'll send you a link.

**Comment by bcoles** [comment]
Hi @wanetty.

Thanks for this. I noticed that the `instructions.txt` file is rather out of date too, but I'll clean that up in a separate PR. Merging.

> I've not looked at Metasploit, but I assume they are using strict Ruby styleguide when calling Methods...

@DeezyE A couple of years ago the Metasploit team updated the core framework to use zeitwerk for dependency auto loading voodoo magic. This requires file names and class names to match and use a consistent format. This is also something we should consider using for BeEF.

**Pull request merged**
