### PR TITLE
New docker compose and makefile with updated dockerfile

### PR DESCRIPTION
**Pull request by MarcPartensky**
# Pull Request

Thanks for submitting a PR! Please fill in this template where appropriate:

## Category
*e.g. Bug, Module, Extension, Core Functionality, Documentation, Tests*

## Feature/Issue Description
**Q:** Please give a brief summary of your feature/fix
**A:** Add docker-compose

**Q:** Give a technical rundown of what you have changed (if applicable)
**A:**  Add docker-compose, makefile and updated dockerfile

## Test Cases
**Q:** Describe your test cases, what you have covered and if there are any use cases that still need addressing.
**A:** No test cases

## Wiki Page
*If you are adding a new feature that is not easily understood without context, please draft a section to be added to the Wiki below.* No new feature

### CODE REVIEW

**Comment by DeezyE** [comment]
Thanks for this submission, I'll pull and test this PR today

**Comment by DeezyE** [comment]
@MarcPartensky with the addition of these changes, is there anything that we need to update in the wiki? https://github.com/beefproject/beef/wiki/Installation#docker-setup

**Comment by MarcPartensky** [comment]
Hi thanks for reviewing the PR. I would suggest adding a section about using the docker-compose.yml file. Something like :

# Run with docker-compose
```sh
# Run
docker-compose up --build
# Remove
docker-compose down
```

**Comment by wheatley** [comment]
hey @MarcPartensky, we're looking to upgrade to 3.x in future, but currently we are trying to align with Kali.
I do like the usage of Ruby 3.x, and we do have a running branch for the 3.x release. (release/0.6.0.0)

Would it be possible to align with ruby 2.7.4 within your Dockerfile, and then resubmitted another PR with ruby 3.x and we'll put that update in the release 0.6.0.0 branch.

**Pull request merged**
