### PR TITLE
Detect Ethereum ENS

### PR DESCRIPTION
**Pull request by bcoles**
Uses the same technique as the Detect TOR module.

### CODE REVIEW

**Comment by DeezyE** [comment]
I'm very curious about this one, how does the .ico play into it?

**Comment by bcoles** [comment]
> I'm very curious about this one, how does the .ico play into it?

If image loaded then the domain resolved. If image not loaded then the domain not resolved.

**Comment by DeezyE** [comment]
And I assume the user needs the appropriate extension to allow this functionality?

**Comment by bcoles** [comment]
> And I assume the user needs the appropriate extension to allow this functionality?

The hooked browser must be capable of resolving ENS to IP addresses in order to connect to ENS domains. This could be done by using a gateway or browser extension.

https://medium.com/the-ethereum-name-service/all-the-ways-you-can-surf-the-decentralized-web-today-bf8e7a42fa27
https://www.thewindowsclub.com/access-blockchain-domains-oi-browsers

It is slow. I've bumped the default timeout from 10s up to 15s.

**Comment by DeezyE** [comment]
> > And I assume the user needs the appropriate extension to allow this functionality?
> 
> The hooked browser must be capable of resolving ENS to IP addresses in order to connect to ENS domains. This could be done by using a gateway or browser extension.
> 
> https://medium.com/the-ethereum-name-service/all-the-ways-you-can-surf-the-decentralized-web-today-bf8e7a42fa27 https://www.thewindowsclub.com/access-blockchain-domains-oi-browsers
> 
> It is slow. I've bumped the default timeout from 10s up to 15s.

I assume ENS doesn't rely on an smart contract anywhere, even 15s is much faster than current block times.

**Comment by bcoles** [comment]
> I assume ENS doesn't rely on an smart contract anywhere, even 15s is much faster than current block times.

Perhaps it loaded faster than 15 seconds because it was cached. :shrug:

Maybe one day ENS will be a useful technology. Until then, users can bump the timeout if they like.

**Pull request merged**
