### PR TITLE
Update Issue/PR templates

### PR DESCRIPTION
**Pull request by jackdwalker**
Thanks for submitting a PR! Please fill in this template where appropriate:

## Category

Documentation

## Feature/Issue Description

Updating issue + PR templates. Also removed the leftover log file from the BrowserStack integration. It's in the .gitignore, so it shouldn't appear again.

### CODE REVIEW

**Comment by bcoles** [comment]
> Please do your best to provide as much information as possible. It greatly aids us in identifying the root cause of your issue :)

A majority of the issue posted are simple "hook doesn't work" which is useful to noone. BeEF logs to console and to file, but most people who have issues are using `beef-xss` service on Parrot/Kali/BlackBox, so they don't see the logs.

It would be good to add some wording about enabling debugging (`beef.client_debug` and `beef.debug`) and retrieving logs, both the client browser console and the logs in `~/.beef/beef.log` and the service logs, which can probably be retrieved using a command like `journalctl -u beef-xss`.

**Comment by jackdwalker** [comment]
Good point. I'll add some wording in to address your feedback.

I am slowly beginning to feel what must have been years of your pain with such issues. A few of us had a laugh at 'I cannot read your mind or your filesystem.' Hopefully this can prevent some of those issues from coming through or at least give us something better to work with.

**Comment by jcrew99** [comment]
@jackdwalker  Any luck on addressing bcoles's feedback? I am happy to try to assist if you do not have availability.

**Comment by uSvfSYJE** [comment]
@jcrew99 @bcoles Addressed - sorry zero time lately -.-

Have a look over it if you get a chance - all good if not; I think it sufficiently addresses the point. Feel free to merge once the tests pass.

**Comment by jackdwalker** [comment]
@jcrew99 @bcoles addressed comments - sorry zero time lately.

Have a look over it if you get the chance - all good if not; I think it sufficiently addresses the bcoles point. Feel free to merge once the tests pass, or let me know if you're happy and I can.

**Pull request merged**
