### PR TITLE
Added the command to install beef from apt

### PR DESCRIPTION
**Pull request by Binula-Kavisinghe**
# Pull Request

Thanks for submitting a PR! Please fill in this template where appropriate:

## Category
*e.g. Bug, Module, Extension, Core Functionality, Documentation, Tests*

## Feature/Issue Description
**Q:** Please give a brief summary of your feature/fix
**A:**

**Q:** Give a technical rundown of what you have changed (if applicable)
**A:**

## Test Cases
**Q:** Describe your test cases, what you have covered and if there are any use cases that still need addressing.
**A:**

## Wiki Page
*If you are adding a new feature that is not easily understood without context, please draft a section to be added to the Wiki below.*

### CODE REVIEW

**Comment by bcoles** [comment]
These instructions are not a replacement for the installation instructions. They may be useful to users if their operating system package manager has a `beef-xss` package. However, most operating systems do not.

Kali, Parrot, and BackBox operating systems are designed for penetration testing purposes. They have a `beef-xss` package. Where as Ubuntu, Debian, etc do not have a `beef-xss` package.

**Comment by DeezyE** [comment]
@Binula-Kavisinghe Thanks for the contribution to Beef, I'm glad that you've taken the time to work on it. As this addresses an issue with beef-xss and breaks this beef repo we won't merge it.
However there's some work that we're planning to do with aligning the Kali package and this one (ideally removing the differences between)
Would you be keen on working on that (or another feature) with us?

**Comment by DeezyE** [comment]
@Binula-Kavisinghe just email discord@bindshell.net if you'd like to join the contributors discord

**Comment by wheatley** [comment]
Closing, please refer to issue #2221

**Pull request closed without merging**
