### PR TITLE
Fix script issue with double quotes in DISTRO_ID extraction

### PR DESCRIPTION
**Pull request by sumithemmadi**
# Pull Request

Thank you for your contribution! Please complete this PR template with the relevant information.

## Category
Bug

## Feature/Issue Description
**Q:** Please give a brief summary of your feature/fix
**A:** This pull request addresses a bug related to the extraction of `DISTRO_ID` in the script. 
The command `grep ID= /etc/os-release | grep -v "BUILD" | grep -v "IMAGE" | cut -d= -f2-  ` returned the value `"endeavouros"` with double quotes, which caused issues in subsequent script checks.

Before

 To provide some context, in a previous pull request, #2930, I introduced the double quotes around `endeavouros` to match the expected format. However, @stephenakq removed the double quotes in https://github.com/beefproject/beef/pull/2930/commits/624176e6acd6c5497faa2f4f419d56a4146b8d99 commit.

I've modified the command to remove the double quotes, resulting in the expected value `endeavouros`.

After

**Q:** Give a technical rundown of what you have changed (if applicable)
**A:** I have modified the command responsible for extracting `DISTRO_ID` from `/etc/os-release`. The change ensures that the extracted value is stored without double quotes using the `sed` command.

## Test Cases
**Q:** Describe your test cases, what you have covered and if there are any use cases that still need addressing.
**A:** I have thoroughly tested this change on various Linux distributions, including EndeavourOS, to ensure it correctly extracts and stores the `DISTRO_ID` without double quotes. The script now functions as expected on these distributions.

### CODE REVIEW

**Comment by stephenakq** [comment]
Thank you for the fix. I will examine the problem and might revert the commit that broke it

**Comment by stephenakq** [comment]
I reverted my commit. Can you please confirm that it is working again?

**Comment by sumithemmadi** [comment]
Yes it's working.

image

**Comment by stephenakq** [comment]
Thank you. I will close this PR. Can you DM in the BeEF discord channel

**Comment by sumithemmadi** [comment]
Sure

**Pull request closed without merging**
