### PR TITLE
Added Arch installer

### PR DESCRIPTION
**Pull request by keeganjk**
Added support for Arch Linux in ./install for an automated installation. Installs dependencies (works on my machine, not sure if there are some I missed...)

Assumes that `ruby` is already installed and in the $PATH.

### CODE REVIEW

**Comment by bcoles** [comment]
Thanks @keeganjk 

LGTM

**Comment by bcoles** [comment]
Intriguing why you pied `cat` to `grep`. `grep` alone should be sufficient. There's almost never a good reason to use `cat` in a script.

**Comment by keeganjk** [comment]
@bcoles Using it didn't work for me... `cat` was a workaround that worked for me and I'm more used to piping something into `grep` as opposed to using `grep` without a pipe.

**Comment by bcoles** [comment]
That seems incredibly unlikely. It's more likely that your `grep` does not support the `^` regex notation without the `-E` flag.

`grep </path/to/file>` will work in every instance where `cat </path/to/file> | grep ...` will work.

**Comment by keeganjk** [comment]
Yeah, I think it was the `^` that was causing it not to work.

**Pull request merged**
