### PR TITLE
fixed auth rate spec failing due to miss configuration

### PR DESCRIPTION
**Pull request by wheatley**
## Category
Bug Tests

To replicate clone current master, bundle install --with development test & run rake
you might be lucky and get a working one first round so run it a few times

## Feature/Issue Description
**Q:** Please give a brief summary of your feature/fix
**A:**

when running rake there was an error with the auth rate spec, and this was not consistent.
traced it to the configuration instance being manipulated by the configuation_spec

Included in the PR, is guard which should help when testing 

**Q:** Give a technical rundown of what you have changed (if applicable)
**A:**

In the configuration spec, the config file is reloaded from the root config file
Also replicated this in the auth_rate spec to try and isolate future issues.

## Test Cases
**Q:** Describe your test cases, what you have covered and if there are any use cases that still need addressing.
**A:**

see spec/beef/api/auth_rate_spec.rb & spec/beef/core/main/configuration_spec.rb

### CODE REVIEW

**Comment by jcrew99** [comment]
The test changes look good but can you expand on the proposed introduction of guard?

**Comment by wheatley** [comment]
Guard allows you to auto run tests running on file changes.

**Comment by jcrew99** [comment]
@wheatley
Can we get a section about Guard added to the BeEF testing wiki?
Happy to merge after that.
https://github.com/beefproject/beef/wiki/BeEF-Testing

**Comment by jcrew99** [comment]
Hey @wheatley,

Happy to merge with the addition to the wiki but the Gemfile.lock is now conflicting.
Can you resolve the issue and i will merge it.

**Pull request merged**
