### PR TITLE
Add ntfy extension

### PR DESCRIPTION
**Pull request by acidobinario**
# Pull Request

Thanks for submitting a PR! Please fill in this template where appropriate:

## Category
 Extension

## Feature/Issue Description
**Q:** Please give a brief summary of your feature/fix
**A:** Adds the option to use ntfy as a notifier

**Q:** Give a technical rundown of what you have changed (if applicable)
**A:** 
I added the following:

**New Module**: Introduced a new notification module under `BeEF::Extension::Notifications::Channels` named **Ntfy**. This module allows BeEF to send notifications through the ntfy platform.

**URI Parsing**: Utilized the URI library to accurately parse the endpoint URL configured in the settings.

**HTTP Basic Authentication**: Implemented HTTP Basic Authentication support for the ntfy endpoint. The username and password are fetched from the configuration and, if present, are used to set the appropriate authentication headers for the HTTP request.

**Notification Sending**: Constructed an HTTP POST request using Net::HTTP::Post. Set the request's content type to 'text/plain' and included a title header 'BeEF Notification'. The body of the request contains the message to be sent to the ntfy platform.

**SSL Support**: Added a check to determine if the provided ntfy endpoint uses HTTPS. If it does, the SSL option for the HTTP client (Net::HTTP) is enabled to ensure secure communication.

**Configuration Integration**: Integrated the new ntfy functionality with the BeEF configuration system. This allows users to specify the ntfy endpoint URL, as well as optional authentication credentials, in the BeEF configuration file.

## Test Cases
**Q:** Describe your test cases, what you have covered and if there are any use cases that still need addressing.
**A:** It ran good using the `docker build` and in a debian local environment with ./install script

## Wiki Page
*If you are adding a new feature that is not easily understood without context, please draft a section to be added to the Wiki below.*

include the following config into the example for the extensions yaml
```yaml
            ntfy:
              enable: false
              endpoint_url: "https://ntfy.sh/beef"
              username: "" # Leave blank if not needed
              password: "" # Leave blank if not needed
```

### CODE REVIEW

**Comment by stephenakq** [comment]
Thanks for submitting the PR @acidobinario. We'll have a look at it soon.

**Comment by stephenakq** [comment]
Hoping to get to this soon @acidobinario

**Comment by acidobinario** [comment]
@stephenakq yeah let me know if you want another thing added or if you need something to test it yourself

**Comment by stephenakq** [comment]
Thank you for you patience. This is still on the list

**Comment by stephenakq** [comment]
I've conducted a preliminary examination, and I'm presently in the process of delving deeper into the details. While I've had a quick look, my thorough review is ongoing, and I'll provide more comprehensive feedback shortly.

**Comment by acidobinario** [comment]
thank you @stephenakq , all insights or feedback that could improve the current state of the PR are appreciated!

**Comment by shaunisdom** [comment]
Hey i apologize… the keyboard had been open on a fish or zsh interactive prompt and I believe tons of requests and various git config or init instances were being haphazardly sent out. I am very sorry about that. I will be far more careful in the future. I didn’t realize the github submissions were being sent outside of the loxcal network. Very embarrassing. Sent from my iPadOn Oct 9, 2023, at 9:12 PM, github-actions[bot] ***@***.***> wrote:﻿
Stale pull request message

**Comment by stephenakq** [comment]
@acidobinario we appreciate your extended patience. It is on the list.

**Pull request merged**
