### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by jcrew99**
# Pull Request

Thanks for submitting a PR! Please fill in this template where appropriate:

## Category
*e.g. Tests*

## Feature/Issue Description
**Q:** Please give a brief summary of your feature/fix
**A:** This is adding the RuboCop Gem to the gemfile, it sets beef to have this specific version for use. Itll allow use to push forward with *linting* beef and updating the code, i plan on doing some changes soon.

**Q:** Give a technical rundown of what you have changed (if applicable)
**A:** Added the 0.88.0 version to the gemfile. Every time beef is installed it will be included as per default. 

## Test Cases
**Q:** Describe your test cases, what you have covered and if there are any use cases that still need addressing.
**A:**
None  yet needed.
## Wiki Page
*If you are adding a new feature that is not easily understood without context, please draft a section to be added to the Wiki below.*
https://github.com/beefproject/beef/wiki/RuboCop
Will be making this look better and explain more

### CODE REVIEW

**Comment by jcrew99** [comment]
Currently at 21433 offences :/ Gonna try and get that down a hundred or so each merge.

**Comment by bcoles** [comment]
> 
> 
> Currently at 21433 offences :/ Gonna try and get that down a hundred or so each merge.

It seems like a lot, but should be fairly simple with `rubocop -a`.

**Comment by jcrew99** [comment]
Yeah, it fixes a massive 27100 of them. The code looks very nice and rubyish but it also breaks BeEF a fair bit. It runs the webserver and will host the pages but the hooks breaks and outputs freeze horror into the terminal.
There may be value in just fixing the errors after running it or stopping the freeze values from being set and seeing what else breaks.
For now tho, im planning on small incremental changes, at least till its possible to tackle what the above things mean.

**Comment by bcoles** [comment]
> 
> 
> Yeah, it fixes a massive 27100 of them. The code looks very nice and rubyish but it also breaks BeEF a fair bit. It runs the webserver and will host the pages but the hooks breaks and outputs freeze horror into the terminal.
> There may be value in just fixing the errors after running it or stopping the freeze values from being set and seeing what else breaks.
> For now tho, im planning on small incremental changes, at least till its possible to tackle what the above things mean.

Right. I was implying `rubocop -a` would resolve most of the issues easily. The updates should still be performed piecemeal rather than all at once.

**Comment by jcrew99** [comment]
ahh okay, i misunderstood. I completely agree in that case

**Pull request merged**
