### PR TITLE
Run BeEF inside docker

### PR DESCRIPTION
**Pull request by ilyaglow**
Hey there!

I added a feature to run beef inside docker. It's based on the `ruby:2.3.0-slim` image.

### How to

```
sudo ./beef-docker
```
That's it.
Behind the scenes script will build the image and run it exposing `:3000` to host and mounting `.beef` to host's `$HOME/.beef`.

I'm open to any suggestions.

Cheers

### CODE REVIEW

**Comment by bcoles** [comment]
Thanks @ ilyaglow 

Unfortunately we're a bit short on developer bandwidth at the moment and don't have time to review this properly.

Regarding suggestions:

You can see a couple of other people's attempts at running BeEF in Docker here:

* https://phocean.net/2017/02/24/beef-docker.html
* https://github.com/phocean/dockerfile-beef
* https://github.com/MalwareLu/docker-beef
* https://hub.docker.com/r/janes/beef/
* http://pythonhackers.com/p/dweinstein/docker-beef

From a quick eyeball of your code, one thing which stands out is the allowed ports. While port 3000 is sufficient for the majority of BeEF's functionality, it's likely that other ports will be required. In particular, the WebSocket ports (61985, 61986). Perhaps also the proxy (port 6789).

**Comment by ilyaglow** [comment]
Thanks for the suggestions @bcoles!

I'm aware of the existing attempts at running BeEF in docker and I appreciate the job this researchers done, but most of those Dockerfiles are outdated and can't be built successfully at the moment, some of them are kind of excessive - it takes really long time to build them. I tried to make the Dockerfile as simple as possible. 

In addition I think it would be great if BeEF have it's own regularly updated official image that people could just pull and run (mean the awesome automated build feature on hub.docker.com). I'm pretty sure everybody will benefit from that and I wonder why nobody sent you a PR related to docker before.

**Comment by bcoles** [comment]
There are a bunch of BeEF images on Docker hub. I haven't tested them.

It looks like BeEF may also be added to Bitnami in the future: https://bitnami.com/stack/beef

**Comment by ilyaglow** [comment]
The only problem I'm facing is that the IP-address of hooked browser always matches the docker bridge IP, so it is hard to figure out from where the browser actually came from.

**Comment by ilyaglow** [comment]
@bcoles it seems like this "Coming soon" badge is hanging there at least [since March 2015](https://web.archive.org/web/20150330093202/https://bitnami.com/stack/beef). It would be great if Bitnami will add a docker for BeEF finally though. 

Btw I just realized that BeEF has tests :) I'll reopen this PR when I'll be sure that the docker here passes all of them.

**Comment by bcoles** [comment]
@ilyaglow cool.

The [BeEF Testing](https://github.com/beefproject/beef/wiki/BeEF-Testing) documentation may help with tests.

Here's the cliff notes:

### Prepare Testing Environment

```bash
$ export BEEF_TEST=1
$ bundle install
```

### List Tests

```bash
$ rake -T
rake all                  # Run all tests
rake automated            # Run automated tests (for Jenkins)
rake bundle_audit         # Run bundle-audit
rake bundle_audit:check   # Check gems for vulns using bundle-audit
rake bundle_audit:run     # Update vulns database and check gems using bundle-audit
rake bundle_audit:update  # Update bundle-audit database
rake integration          # Run integration unit tests
rake msf                  # Run MSF unit tests
rake quick                # Run quick tests
rake rdoc                 # Generate API documentation to doc/rdocs/index.html
rake rdoc:clobber_rdoc    # Remove RDoc HTML files
rake rdoc:rdoc            # Build RDoc HTML files
rake rdoc:rerdoc          # Rebuild RDoc HTML files
rake ssl:create           # Create a new SSL certificate
rake ssl:replace          # Re-generate SSL certificate
rake unit                 # Run integration unit tests
```

### Run Tests

```
$ rake unit
$ rake integration
```

**Comment by ilyaglow** [comment]
So this is what I [have so far](https://gist.github.com/ilyaglow/470f386449005e372314851e71de7a81):
* Unit tests: 100% of tests passed
* Integration tests: ~80% of tests passed

### Thoughts about integration tests fails
The hardest thing to me is to install latest Firefox in the container. The `ruby:2.3.0-slim` is based on Debian Jessie image, which has only Firefox ESR version 52 in the repo - too old for geckodriver (it is recommended to use 53+), so I think probably this is why a lot of tests failed, but I do not really have much time right now to prove that.

Actually I think it would be amazing if integration tests could use something like Selenium Grid so Capybara will be capable to use remote driver for different browsers and different browser versions. What you think? Maybe this feature worth a separated issue if it is not on the road map already.

**Pull request closed without merging**
