### PR TITLE
Couple of fixes & improvements

### PR DESCRIPTION
**Pull request by mgeeky**
Added top-ports set according to Fyodor's nmap-services open-frequency column sorted and added parsing of user-input custom domains for Get-Visited-Domains module.

### CODE REVIEW

**Comment by mgeeky** [comment]
'top' parameter name could be renamed to for instance 'frequent', also dunno whether those changes (like additional parameters) won't affect BeEF's REST API.

**Comment by bcoles** [comment]
@mgeeky  Thanks for this and your previous contributions. In the future, can you please do one PR for each updated module? This will make life easier for reviewers.

**Comment by bcoles** [comment]
@mgeeky This PR looks ready to merge, however, can you change the default link from redtube to something more safe for work?

**Comment by mgeeky** [comment]
@bcoles : Sure thing, I'll try to remember that. Safe-for-work ammend pushed :-)

**Comment by bcoles** [comment]
Merged. Thanks @mgeeky

**Pull request merged**
