### PR TITLE
Add mysql to gem

### PR DESCRIPTION
**Pull request by nemanjan00**
Add mysql to gem

### CODE REVIEW

**Comment by bcoles** [comment]
Thanks but MySQL and PostgreSQL gems are commented out for a reason. SQLite is the default database.

**Comment by nemanjan00** [comment]
But, how do I install mysql/Postgres then?

**Comment by bcoles** [comment]
Install MySQL or PostgreSQL using the binary installer from the associated website, or via packages.

Then uncomment the associated gem in the `Gemfile` and run `bundle install`

**Comment by nemanjan00** [comment]
What about us who are installing it using package manager? 

After running bundle install inside it, now I can not get it to work for normal user.

**Comment by bcoles** [comment]
The gems don't contain all the required functionality. Instead, the gems provide Ruby bindings.

As such, whichever data storage method you choose, you'll also need to install the associated software / operating system packages.

If all data storage gems were enabled (SQLite, PostgreSQL, MySQL), then everyone would need to install all three to get BeEF installed, which is overkill and error prone.

SQLite is the default as it's the easiest to set up (in theory). Using a default "known good" configuration is preferred to the shotgun approach.

**Pull request closed without merging**
